# Generated by Django 3.2.5 on 2021-07-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('AssetName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Server', models.CharField(max_length=20)),
                ('Port', models.IntegerField(blank=True, null=True)),
                ('IP', models.CharField(max_length=100)),
                ('Hostname', models.CharField(max_length=100)),
                ('MAC', models.CharField(max_length=100)),
                ('OS', models.CharField(max_length=100)),
            ],
        ),
    ]
