# Generated by Django 3.2.5 on 2021-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='LastUpdated',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='Status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
