# Generated by Django 3.2.4 on 2021-07-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0002_auto_20210720_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='LastSeen',
            field=models.TimeField(null=True),
        ),
    ]
