# Generated by Django 3.2.4 on 2021-07-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0003_response_lastseen'),
        ('gridapp', '0003_response_lastseenalive'),
    ]

    operations = [
    ]
