# Generated by Django 3.2.5 on 2021-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0004_response_domaininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=50)),
                ('Server', models.CharField(max_length=20)),
                ('Port', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='AssetName',
        ),
        migrations.RemoveField(
            model_name='response',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='response',
            name='Port',
        ),
        migrations.RemoveField(
            model_name='response',
            name='Server',
        ),
        migrations.RemoveField(
            model_name='response',
            name='Username',
        ),
        migrations.AlterField(
            model_name='response',
            name='IP',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
