# Generated by Django 3.2.4 on 2021-07-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0004_merge_20210722_0814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='LastSeen',
        ),
        migrations.AddField(
            model_name='response',
            name='DomainInfo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
